#Eureka Server Configurations

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8540/eureka/
  instance:
    hostname: localhost
